added js lint

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -4,13 +4,9 @@ set -euo pipefail
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 PROJECT_ROOT_DIR="${SCRIPT_DIR}/.."
 
-GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)
-
-if [[ -z "$GO_FILES" ]]; then
-  exit 0
-fi
-
 cd "${PROJECT_ROOT_DIR}"
-./bin/lint-new
 
-git add $GO_FILES
+if ! ./bin/lint-new; then
+  echo "Lint failed; commit failed." >&2
+  exit 1
+fi
